//
//  CardContext.swift
//  楊昀恩生日欸
//
//  Created by Andy Lin on 2024/2/6.
//

import Foundation
import SwiftUI


final class CardContext {
    fileprivate static let pushTimes = UserDefaults.standard.integer(forKey: UserDefaultKeys.notificationPushTimes)
    
    let content: [CardContentItem] = [
        CardContentItem(text: "Tap to see moreeeee"),
        CardContentItem(text: "Left is back"),
        CardContentItem(text: "Right is continue"),
        CardContentItem(text: "welcome to your birthday greeting"),
        CardContentItem(text: "just watch "),
        CardContentItem(text: "and"),
        CardContentItem(text: "enjoy it :D"),
        CardContentItem(text: ""),
        CardContentItem(text: "欸你好"),
        CardContentItem(text: "這是我給你的生日禮物"),
        CardContentItem(text: "驚不驚喜 E不EY"),
        CardContentItem(text: "想必沒人給你過這種生日禮物8️⃣"),
        CardContentItem(text: "哎呀你那時候就在那裡問"),
        CardContentItem(text: "不是說了之後自己會知道唄"),
        CardContentItem(text: "總之"),
        CardContentItem(text: "你一定是非常高興收到這個對吧:D"),
        CardContentItem(text: "欸你看"),
        CardContentItem(text: "你總共開了這個app \(pushTimes)次ㄟ"),
        CardContentItem(text: "好啦這個功能是那次更新才加上去ㄉ\n所以可能會不準:D"),
        CardContentItem(text: "嗯對 ㄜ"),
        CardContentItem(text: "生日禮物的部分"),
        CardContentItem(text: "我很抱歉🙃"),
        CardContentItem(text: "🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️"),
        CardContentItem(text: ""),
        CardContentItem(text: "這就當作是你給我的禮物的回禮好ㄌ"),
        CardContentItem(text: "好啦，㊗️你生日快樂"),
        CardContentItem(text: "", image: Image("BirthdayGreeting")),
        CardContentItem(text: "用你的魔法打敗你:D"),
        CardContentItem(text: "好啦"),
        CardContentItem(text: "我多想一次"),
        CardContentItem(text: "試都考高 比賽都贏 不會遇到爛桃花"),
        CardContentItem(text: "多送第四個給你自己選ㄅ"),
        CardContentItem(text: "有空記得常來看看這些廢話(·▷．)"),
        CardContentItem(text: "搞不好會有你意想不到的東東:D"),
        CardContentItem(text: "好啦 廢話好像有點太多ㄌ\n講點正經的好了"),
        CardContentItem(text: "這段從國小開始的緣分（？"),
        CardContentItem(text: "好像是快要結束了餒：（"),
        CardContentItem(text: "這樣看一看 雖然我們才比較熟快一年而已"),
        CardContentItem(text: "阿但是好像真的挺多東西能拿出來講"),
        CardContentItem(text: "但這一年裡面我不知道惹了多少事:D"),
        CardContentItem(text: "而且好像也挺多事情發生ㄉ"),
        CardContentItem(text: "從一開始你來找我 那位柏寬🈹"),
        CardContentItem(text: "還有3月的那個11的事情（好我很對不起他：）"),
        CardContentItem(text: "到大概4月之後的自信🈹&那位人見人愛ㄉ婷涵:D"),
        CardContentItem(text: "之後你開始跟我說10一天到晚在那裡靠腰很煩"),
        CardContentItem(text: "後來6 7月"),
        CardContentItem(text: "ㄜ 耳環事件我就不多說了"),
        CardContentItem(text: "後面的我好像也幾乎忘了"),
        CardContentItem(text: "欸對"),
        CardContentItem(text: "還有你給我生日禮物"),
        CardContentItem(text: "不用客氣la"),
        CardContentItem(text: "阿但是沒關係"),
        CardContentItem(text: "在這之間充斥著所有時間線的就是你的一某:D"),
        CardContentItem(text: "雖然最近你不怎麼理我"),
        CardContentItem(text: "訊息都過好幾個小時才回：（"),
        CardContentItem(text: "啊但我還是回禮一下好了"),
        CardContentItem(text: "嗯對還是感謝一下你教我歷史好了:D"),
        CardContentItem(text: "還有那個設計到一半的東東：（"),
        CardContentItem(text: "你呢"),
        CardContentItem(text: "都會在那邊"),
        CardContentItem(text: "欸很扯欸 校車上/回去訊息講"),
        CardContentItem(text: "然後講著講著就不講ㄌ"),
        CardContentItem(text: "在那裡吊胃口"),
        CardContentItem(text: "。"),
        CardContentItem(text: "說到這個"),
        CardContentItem(text: "你還沒跟我說你為什麼你要在那裡"),
        CardContentItem(text: "什麼比目魚 中央空調ㄉ"),
        CardContentItem(text: "跟我講啦拜託( •᷄⌓•᷅ )"),
        CardContentItem(text: ""),
        CardContentItem(text: "好啦"),
        CardContentItem(text: "最後"),
        CardContentItem(text: "再祝你生日快樂一次"),
        CardContentItem(text: "不要太在意其他人怎麼評價你la"),
        CardContentItem(text: "他們愛嘴賤就讓他們去賤唄"),
        CardContentItem(text: "還有"),
        CardContentItem(text: "謝謝你"),
        CardContentItem(text: ":D"),
        CardContentItem(text: "", isShowButton: true),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: "ㄟ", isShowButton: false),
        CardContentItem(text: "你怎麼還在"),
        CardContentItem(text: "不要太喜歡這個啦:D"),
        CardContentItem(text: "好啦"),
        CardContentItem(text: "給你看一些製作的東東好ㄌ"),
        CardContentItem(text: "你看我多用心ㄚ", image: Image("MakingDetail")),
        CardContentItem(text: "", isShowButton: true),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: "偷偷跟你講個秘密", isShowButton: false),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: "期待嗎"),
        CardContentItem(text: "期待就先跟我講這個是什麼👀", image: Image("ReasonOfFlounder")),
        CardContentItem(text: ""),
        CardContentItem(text: "", isShowButton: true),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: "吼呦", isShowButton: false),
        CardContentItem(text: "你怎麼還在啦"),
        CardContentItem(text: "你是不是真的以為我會寫什麼👀"),
        CardContentItem(text: "沒有這種事情好ㄇ"),
        CardContentItem(text: "我可以給你看你的照片👌🏻"),
        CardContentItem(text: "雖然沒多少就是了：）"),
        CardContentItem(text: "這是你在校車上被偷拍:D", image: Image("SheOnSchoolBus")),
        CardContentItem(text: "還有同場加映", image: Image("SheOnSchoolBus2")),
        CardContentItem(text: "欸還有你在那裡一某", image: Image("EmoText")),
        CardContentItem(text: "不要忘記這個你說眼睛ㄆㄧㄚˊ掉ㄉ", image: Image("SchoolFail")),
        CardContentItem(text: "喔對 還有這個"),
        CardContentItem(text: "我直接躲到超旁邊:D", image: Image("GraduationTrip-GroupPhoto")),
        CardContentItem(text: "你知道這張辛拉麵那一天一直說8拍得很好，講超久：）", image: Image("GraduationTrip")),
        CardContentItem(text: "還有這個啦 皮老闆:D", image: Image("Plankton")),
        CardContentItem(text: "好啦後面是真的沒有東西ㄌ"),
        CardContentItem(text: "給我按那個返回", isShowButton: true),
        CardContentItem(text: "繼續按你也按不出什麼東西:D"),
        CardContentItem(text: ""),
        CardContentItem(text: "夠了我要強制驅離ㄌ")
    ]
    
    let contentAfterVisit10Times: [CardContentItem] = [
        CardContentItem(text: "欸你知道ㄇ"),
        CardContentItem(text: "這是你看超過10次之後會出現ㄉ"),
        CardContentItem(text: "如果你想要回去原本ㄉ東東"),
        CardContentItem(text: "多看完幾次就會回去ㄌ:D（大概2次ㄅ）"),
        CardContentItem(text: "既然你都看這麼多次ㄌ"),
        CardContentItem(text: "想必是對這東西很有愛對吧👀"),
        CardContentItem(text: "好啦"),
        CardContentItem(text: "說真的"),
        CardContentItem(text: "如果你真的看到這個了"),
        CardContentItem(text: "我很感動"),
        CardContentItem(text: "是真的很感動：）"),
        CardContentItem(text: "還有"),
        CardContentItem(text: "沒帶到你的氣球我真的很抱歉：（"),
        CardContentItem(text: "欸對你知道ㄇ"),
        CardContentItem(text: "這個東東ㄚ"),
        CardContentItem(text: "過90天就會消失了"),
        CardContentItem(text: "不是我刪掉他"),
        CardContentItem(text: "是他本身TestFlight的限制"),
        CardContentItem(text: "如果你想一直留著的話"),
        CardContentItem(text: "記得叫我去更新:D"),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: "不知道你過得怎樣"),
        CardContentItem(text: "也不知道你什麼時候會看到這個"),
        CardContentItem(text: "也許根本沒有看到也說不定:D"),
        CardContentItem(text: ""),
        CardContentItem(text: "如果"),
        CardContentItem(text: "你看到這個"),
        CardContentItem(text: "祝你會考能順利考上你嚮往的學校"),
        CardContentItem(text: "唉呀"),
        CardContentItem(text: "我人真的太好了:D"),
        CardContentItem(text: ""),
        CardContentItem(text: "ㄞ"),
        CardContentItem(text: "國中生活還真的要結束了欸"),
        CardContentItem(text: ""),
        CardContentItem(text: "好..不真實（？"),
        CardContentItem(text: "一切都發生得那麼快"),
        CardContentItem(text: "一轉眼間"),
        CardContentItem(text: "從我們開始認識的國二"),
        CardContentItem(text: "到現在已經他媽國三要畢業了"),
        CardContentItem(text: "。"),
        CardContentItem(text: "我"),
        CardContentItem(text: "不知道講什麼"),
        CardContentItem(text: "過得好快"),
        CardContentItem(text: "真的好快"),
        CardContentItem(text: "就好像是一段旅行"),
        CardContentItem(text: "感覺才剛踏上啟程的路途"),
        CardContentItem(text: "馬上就結束了一樣"),
        CardContentItem(text: "我也知道除了11那群以外對你來說基本沒什麼好留念ㄉ"),
        CardContentItem(text: "（聽說你覺得都是在勾心鬥角:D"),
        CardContentItem(text: "好ㄅ"),
        CardContentItem(text: "感覺我也想不到什麼要講的ㄌ"),
        CardContentItem(text: "剩的如果你還想聽"),
        CardContentItem(text: "你去訊息提醒我講:D\n我還有記得的話la"),
        CardContentItem(text: "那就先醬子唄", isShowButton: true),
        CardContentItem(text: "可以離開ㄌ"),
        CardContentItem(text: "後面沒東西了"),
        CardContentItem(text: ""),
        CardContentItem(text: "")
    ]
    
    let cardNonsense: [CardContentItem] = [
        CardContentItem(text: "好啦不要再點ㄌ"),
        CardContentItem(text: "快點點那個信封啦"),
        CardContentItem(text: ""),
        CardContentItem(text: ""),
        CardContentItem(text: "吼呦"),
        CardContentItem(text: "聽不懂ㄇ"),
        CardContentItem(text: "我要強制你進去ㄌ")
    ]
}
